//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingLedger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankingLedger.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountCaption {
            get {
                return ResourceManager.GetString("AmountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check balance.
        /// </summary>
        internal static string CheckBalanceCaption {
            get {
                return ResourceManager.GetString("CheckBalanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseCaption {
            get {
                return ResourceManager.GetString("CloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        internal static string CreateNewAccountCaption {
            get {
                return ResourceManager.GetString("CreateNewAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateCaption {
            get {
                return ResourceManager.GetString("DateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string DepositCaption {
            get {
                return ResourceManager.GetString("DepositCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit exceeds account limit..
        /// </summary>
        internal static string DepositExceedsAccountLimitMessage {
            get {
                return ResourceManager.GetString("DepositExceedsAccountLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit successful..
        /// </summary>
        internal static string DepositSuccessfulMessage {
            get {
                return ResourceManager.GetString("DepositSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number..
        /// </summary>
        internal static string EnterANumberMessage {
            get {
                return ResourceManager.GetString("EnterANumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstNameCaption {
            get {
                return ResourceManager.GetString("FirstNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0} {1}!.
        /// </summary>
        internal static string HelloUserMessage {
            get {
                return ResourceManager.GetString("HelloUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many dollars would you like to deposit?.
        /// </summary>
        internal static string HowManyDollarsToDepositMessage {
            get {
                return ResourceManager.GetString("HowManyDollarsToDepositMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many dollars you like to withdraw?.
        /// </summary>
        internal static string HowManyDollarsToWithdrawMessage {
            get {
                return ResourceManager.GetString("HowManyDollarsToWithdrawMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdCaption {
            get {
                return ResourceManager.GetString("IdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty..
        /// </summary>
        internal static string InputCannotBeEmptyMessage {
            get {
                return ResourceManager.GetString("InputCannotBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount..
        /// </summary>
        internal static string InvalidAmountMessage {
            get {
                return ResourceManager.GetString("InvalidAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option..
        /// </summary>
        internal static string InvalidOptionMessage {
            get {
                return ResourceManager.GetString("InvalidOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastNameCaption {
            get {
                return ResourceManager.GetString("LastNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogInCaption {
            get {
                return ResourceManager.GetString("LogInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        internal static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login unsuccessful..
        /// </summary>
        internal static string LoginUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOutCaption {
            get {
                return ResourceManager.GetString("LogOutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you are not logged in. 
        ///Please choose an option by entering a number..
        /// </summary>
        internal static string NotLoggedInChooseOptionMessage {
            get {
                return ResourceManager.GetString("NotLoggedInChooseOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction history..
        /// </summary>
        internal static string NoTransactionHistoryMessage {
            get {
                return ResourceManager.GetString("NoTransactionHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Balance.
        /// </summary>
        internal static string PostBalanceCaption {
            get {
                return ResourceManager.GetString("PostBalanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeCaption {
            get {
                return ResourceManager.GetString("TypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string UsernameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UsernameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameCaption {
            get {
                return ResourceManager.GetString("UsernameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View transaction history.
        /// </summary>
        internal static string ViewTransactionHistoryCaption {
            get {
                return ResourceManager.GetString("ViewTransactionHistoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Banking Ledger!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal exceeds account limit..
        /// </summary>
        internal static string WithdrawalExceedsAccountLimitMessage {
            get {
                return ResourceManager.GetString("WithdrawalExceedsAccountLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal successful..
        /// </summary>
        internal static string WithdrawalSuccessfulMessage {
            get {
                return ResourceManager.GetString("WithdrawalSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string WithdrawCaption {
            get {
                return ResourceManager.GetString("WithdrawCaption", resourceCulture);
            }
        }
    }
}
